language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  app: gentle-lake-89085
  api_key:
    secure: BwjdpNX6P0ZSmLMAUWzzzw4qLKDvhRjegd438gBuxZVvrPnleaMJ1wvUioGVwTVAmB2Vj1vtcw10RJbUxxiHdeLUgUNed7Jbdhm5AMpimKNrcM6iANmBKnpYhXNXBRR2fi9wSnvFZny+Qk17H/acoFfM3GaB0RbHXX04ivEwIYpu5LagOJoRn3ASP6AKPAT6FrOH8A1UZOxMQrOJ+kZ5YWiCyXXinF903YVxlg95jiuaXyzbeZdMHWm3gtbq6BO8EdjYSUNdYUBsW4kHEcgQESf61FENqGDw2z1bZlUQM4cCfBXv07+O7kkJXq6qZiSD3dulFeYvGw/l6G6XAde6nb2uA9dUk0CsEp2v4ylDDDr7QSQx8ValFGt31piRbtOwGjNluveaXUEaxuIdyFYPEzYjHS4GZhUNi2lIuDYHqiNSufFCMkk/TuhIiKOsl6jmtQ5UonoYAZlEKaq8ybNyaTFVEE9ASobgmuivsnozvu9VxwnQdi3WOkT1WdUmolYKhw7CkqVm079Yt2aosyO839QyJ+6AGtZr6TGj0dfCpEC34H6iT04WTT6+qvTVbfUdNDJ2u0yXuP6OJkVpyCnndW7Dxzpoyn0lrGpzCS9PHj+jMfMZaHeWHWN1uRk+A7my1n5j5d/4mdfEn+2dF1MwbfQ8G5908jdom4XswKCDmAU=
